openapi: 3.0.0
servers:
  - description: local Backend Address
    url: http://localhost:8080/api
info:
  description: Dies ist die API des Webshop Backends
  version: "1.0.0"
  title: WEBSHOP API
  contact:
    email: mirco_christoph.mueller@edu.fhdw.de

tags:
  - name: admins
    description: Secured Admin-only calls
  - name: users
    description: Operations available to regular users

paths:
  /user/login:
    get:
      tags:
        - users
        - admins
      summary: login api returns user object
      operationId: login
      description: |
        by passing the correct user authentication via basic auth you get a json return value containing a json value.
      responses:
        '200':
          description: returning json body with user object
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserObject'
        '400':
          description: Object not existent (worst Case) or authentication failed
  /user/edit:
    put:
      tags:
        - users
        - admins
      summary: verändert den User der Übertragen wird.
components:
  schemas:
    UserObject:
      type: object
      required:
        - username
        - password
      properties:
        id:
          type: number
          example: 123
        username:
          type: string
          example: user
        birth:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        password:
          type: string
          example: "Test1234"
        address:
          $ref: '#/components/schemas/addressObject'
    addressObject:
      type: array
      items:
        type: object
        required:
          - id
          - street
          - postal Code
        properties:
          id:
            type: number
            example: 123
          username:
            type: string
            example: user3
    HelloWorld:
      type: object
      required: 
        - value
      properties:
        value:
          type: string
          example: "dies ist der Hello World Test"