version: '3'
services:
  postgres:
    restart: always
    build: 
      context: ./docker/postgres
    env_file:
      - ./docker/postgres/database.env # configure postgres
    ports:
      - '5432:5432'
      
  backend:
    restart : always
    build:
      context:  ./
      dockerfile: ./src/main/docker/Dockerfile.Multistage
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/shop
      - quarkus.log.level=INFO
      - quarkus.log.category."org.hibernate".level=INFO
      - quarkus.hibernate-orm.database.generation=update
    depends_on:
      - postgres
    ports:
      - '8080:8080'